workspace:
  build: docker-images/data
  extends:
    file: docker-compose.local.yml
    service: workspace_container

shell:
  build: docker-images/installer
  privileged: true
  command: /bin/zsh
  user: dockerdev
  volumes_from:
      - workspace
  environment:
      # USER ID of your host user default to 1000 (boot2docker)
      # DEV_UID: 502
      # GID of your host user default to 20 (boot2docker)
      # DEV_GID: 20

mysql:
  image: mysql:latest
  ports:
    - "3306:3306"
  volumes_from:
    - workspace
  environment:
    MYSQL_DATABASE: appdb
    MYSQL_USER: app_dbuser
    MYSQL_PASSWORD: app_dbpwd
    MYSQL_ROOT_PASSWORD: MYROOTPWD

php:
  build: docker-images/php/5.6-dev
  ports:
      #web port
      - "80:80"
      #zray port
      - "10081:10081"
  links:
      - mysql
  volumes_from:
      - workspace
  privileged: true
  environment:
      # USER ID of your host user default to 1000 (boot2docker)
      # DEV_UID: 502
      # GID of your host user default to 20 (boot2docker)
      # DEV_GID: 20
      BASE_URL: http://app.dev.local
      APPLICATION_ENV: development
